version: "3.3"
services:
  # MySQL 容器
  mysql:
    container_name: crmeb_mysql
    image: mysql:5.7
    ports:
      - 3336:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'crmeb'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'crmeb'
    command:
       --character-set-server=utf8mb4
       --collation-server=utf8mb4_general_ci
       --explicit_defaults_for_timestamp=true
       --lower_case_table_names=1
       --max_allowed_packet=128M
       --default-authentication-plugin=mysql_native_password
       --sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    working_dir: /var/lib/mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    networks:
      app_net:
        ipv4_address: 192.168.10.11

  # Redis 容器
  redis:
    container_name: crmeb_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 192.168.10.10

  # PHP-FPM 容器
  phpfpm:
    container_name: crmeb_php
    build:
      context: ./php
      dockerfile: Dockerfile   # 使用下面改好的 Dockerfile
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 9000:9000
      - 20002:20002
      - 20003:20003
    tmpfs: /var/temp
    working_dir: /var/www
    volumes:
      - ../crmeb:/var/www
      - ../crmeb/runtime:/var/www/runtime
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    networks:
      app_net:
        ipv4_address: 192.168.10.90

  # Nginx 容器
  nginx:
    container_name: crmeb_nginx
    image: nginx:alpine
    restart: always
    ports:
      - 8011:80
    depends_on:
      - phpfpm
    environment:
      TZ: Asia/Shanghai
    working_dir: /var/www
    volumes:
      - ../crmeb:/var/www
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    networks:
      app_net:
        ipv4_address: 192.168.10.80

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
